; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define version_dir "REPLACE_VERSION_UNDERBAR"
#define version_dot "REPLACE_VERSION_DOT"

#define MyAppName "Egaroucid"
#define MyAppVersion version_dot + " Windows"
#define MyAppPublisher "Takuto Yamana"
#define MyAppURL "https://www.egaroucid.nyanyan.dev/"
#define EGAROUCID_RELEASE_DIR "./../"
#define EGAROUCID_SIMD_EXE "Egaroucid_" + version_dir + "_SIMD.exe"
#define EGAROUCID_SIMD_AMD_EXE "Egaroucid_" + version_dir + "_SIMD_AMD.exe"
#define EGAROUCID_AVX512_EXE "Egaroucid_" + version_dir + "_AVX512.exe"
#define EGAROUCID_AVX512_AMD_EXE "Egaroucid_" + version_dir + "_AVX512_AMD.exe"
#define EGAROUCID_GENERIC_EXE "Egaroucid_" + version_dir + "_Generic.exe"

[Setup]
PrivilegesRequired=none
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}_{#version_dir}
DisableProgramGroupPage=yes
LicenseFile={#EGAROUCID_RELEASE_DIR}\files\license.txt
OutputBaseFilename={#MyAppName}_{#version_dir}_Installer
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
SetupIconFile={#EGAROUCID_RELEASE_DIR}\files\favicon.ico
WizardSmallImageFile={#EGAROUCID_RELEASE_DIR}\files\resources\img\icon_wizard.bmp
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";

[Files]
Source: "{#EGAROUCID_SIMD_EXE}"; DestDir: "{app}"; Flags: ignoreversion; Check: ShouldInstall_SIMD
Source: "{#EGAROUCID_SIMD_AMD_EXE}"; DestDir: "{app}"; Flags: ignoreversion; Check: ShouldInstall_SIMD_AMD
Source: "{#EGAROUCID_AVX512_EXE}"; DestDir: "{app}"; Flags: ignoreversion; Check: ShouldInstall_AVX512
Source: "{#EGAROUCID_AVX512_AMD_EXE}"; DestDir: "{app}"; Flags: ignoreversion; Check: ShouldInstall_AVX512_AMD
Source: "{#EGAROUCID_GENERIC_EXE}"; DestDir: "{app}"; Flags: ignoreversion; Check: ShouldInstall_GENERIC
Source: "{#EGAROUCID_RELEASE_DIR}\files\LICENSE"; DestDir: "{app}";
Source: "{#EGAROUCID_RELEASE_DIR}\files\resources\*"; DestDir: "{app}\resources"; Flags: recursesubdirs;
Source: "{#EGAROUCID_RELEASE_DIR}\files\AppData\Egaroucid\*"; DestDir: "{userappdata}\Local\Egaroucid"; Flags: recursesubdirs;
Source: "{#EGAROUCID_RELEASE_DIR}\files\Documents\Egaroucid\*"; DestDir: "{userdocs}\Egaroucid"; Flags: recursesubdirs;
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#EGAROUCID_SIMD_EXE}"; Check: ShouldInstall_SIMD
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#EGAROUCID_SIMD_AMD_EXE}"; Check: ShouldInstall_SIMD_AMD
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#EGAROUCID_AVX512_EXE}"; Check: ShouldInstall_AVX512
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#EGAROUCID_AVX512_AMD_EXE}"; Check: ShouldInstall_AVX512_AMD
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#EGAROUCID_GENERIC_EXE}"; Check: ShouldInstall_GENERIC
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#EGAROUCID_SIMD_EXE}"; Check: ShouldInstall_SIMD; Tasks: desktopicon
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#EGAROUCID_SIMD_AMD_EXE}"; Check: ShouldInstall_SIMD_AMD; Tasks: desktopicon
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#EGAROUCID_AVX512_EXE}"; Check: ShouldInstall_AVX512; Tasks: desktopicon
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#EGAROUCID_AVX512_AMD_EXE}"; Check: ShouldInstall_AVX512_AMD; Tasks: desktopicon
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#EGAROUCID_GENERIC_EXE}"; Check: ShouldInstall_GENERIC; Tasks: desktopicon

[Run]
Filename: "{app}\{#EGAROUCID_SIMD_EXE}"; Check: ShouldInstall_SIMD; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\{#EGAROUCID_SIMD_AMD_EXE}"; Check: ShouldInstall_SIMD_AMD; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\{#EGAROUCID_AVX512_EXE}"; Check: ShouldInstall_AVX512; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\{#EGAROUCID_AVX512_AMD_EXE}"; Check: ShouldInstall_AVX512_AMD; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\{#EGAROUCID_GENERIC_EXE}"; Check: ShouldInstall_GENERIC; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "https://www.egaroucid.nyanyan.dev/ja/usage/"; Flags: shellexec postinstall runmaximized; Description: "使い方を表示"; Languages: japanese
Filename: "https://www.egaroucid.nyanyan.dev/en/usage/"; Flags: shellexec postinstall runmaximized; Description: "Show Usage"; Languages: english

[Code]
function IsProcessorFeaturePresent(Feature: Integer): Boolean;
external 'IsProcessorFeaturePresent@kernel32.dll stdcall';

function IsAMDProcessor(): Boolean;
var
  i: Integer;
  Vendor: string;
begin
  Result := False;
  i := 0;

  while RegQueryStringValue(HKLM,
    Format('HARDWARE\DESCRIPTION\System\CentralProcessor\%d', [i]),
    'VendorIdentifier', Vendor) do
  begin
    if Pos('AuthenticAMD', Vendor) > 0 then
    begin
      Result := True;
      Exit;
    end;
    Inc(i);
  end;
end;

function ShouldInstall_SIMD: Boolean;
begin
  Result := IsProcessorFeaturePresent(40) and (not IsProcessorFeaturePresent(41)) and (not IsAMDProcessor()); {AVX2 & !AVX512 & !AMD}
end;

function ShouldInstall_SIMD_AMD: Boolean;
begin
  Result := IsProcessorFeaturePresent(40) and (not IsProcessorFeaturePresent(41)) and IsAMDProcessor(); {AVX2 & !AVX512 & AMD}
end;

function ShouldInstall_AVX512: Boolean;
begin
  Result := IsProcessorFeaturePresent(40) and IsProcessorFeaturePresent(41) and (not IsAMDProcessor()); {AVX2 & AVX512 & !AMD}
end;

function ShouldInstall_AVX512_AMD: Boolean;
begin
  Result := IsProcessorFeaturePresent(40) and IsProcessorFeaturePresent(41) and IsAMDProcessor(); {AVX2 & AVX512 & AMD}
end;

function ShouldInstall_GENERIC: Boolean;
begin
  Result := not IsProcessorFeaturePresent(40); {!AVX2}
end;

procedure AddMissingPath(var MissingPaths: string; Path: string);
begin
  if MissingPaths <> '' then
    MissingPaths := MissingPaths + #13#10;
  MissingPaths := MissingPaths + Path;
end;

procedure CheckInstalledFile(Path: string; var MissingPaths: string);
begin
  if not FileExists(Path) then
    AddMissingPath(MissingPaths, Path);
end;

procedure CheckInstalledExe(FileName: string; ShouldInstall: Boolean; var MissingPaths: string);
begin
  if ShouldInstall then
    CheckInstalledFile(ExpandConstant('{app}\' + FileName), MissingPaths);
end;

procedure CheckInstalledFiles;
var
  MissingPaths: string;
begin
  MissingPaths := '';

  CheckInstalledExe('{#EGAROUCID_SIMD_EXE}', ShouldInstall_SIMD, MissingPaths);
  CheckInstalledExe('{#EGAROUCID_SIMD_AMD_EXE}', ShouldInstall_SIMD_AMD, MissingPaths);
  CheckInstalledExe('{#EGAROUCID_AVX512_EXE}', ShouldInstall_AVX512, MissingPaths);
  CheckInstalledExe('{#EGAROUCID_AVX512_AMD_EXE}', ShouldInstall_AVX512_AMD, MissingPaths);
  CheckInstalledExe('{#EGAROUCID_GENERIC_EXE}', ShouldInstall_GENERIC, MissingPaths);

  CheckInstalledFile(ExpandConstant('{app}\LICENSE'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{app}\resources\eval.egev2'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{app}\resources\eval_move_ordering_end.egev'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{app}\resources\hash\hash25.eghs'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{app}\resources\hash\hash26.eghs'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{app}\resources\hash\hash27.eghs'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{app}\resources\img\icon.png'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{app}\resources\languages\languages.json'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{app}\resources\openings\japanese\openings.txt'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{app}\resources\xot\openingslarge.txt'), MissingPaths);

  CheckInstalledFile(ExpandConstant('{userappdata}\Local\Egaroucid\version.txt'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{userappdata}\Local\Egaroucid\ai_settings\README.txt'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{userappdata}\Local\Egaroucid\display_settings\README.txt'), MissingPaths);

  CheckInstalledFile(ExpandConstant('{userdocs}\Egaroucid\book.egbk3'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{userdocs}\Egaroucid\empty_book.egbk3'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{userdocs}\Egaroucid\games\summary.csv'), MissingPaths);
  CheckInstalledFile(ExpandConstant('{userdocs}\Egaroucid\screenshots\README.txt'), MissingPaths);

  if MissingPaths <> '' then
  begin
    MsgBox(
      'Installation finished, but the following files were not found:' + #13#10 + #13#10 + MissingPaths,
      mbError,
      MB_OK);
    Abort;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    CheckInstalledFiles;
end;
